let blog_data ={
    status:"ok",
    totalResults:6,
    blogMainContents:[
        {
            id:1,
            title:"Free Open-Source Icons_Smashing Magazine",
            text:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore...Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore...Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore...Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invid",
            urlToImage:"./images/blog1.jpg",
            react:"⭐⭐⭐⭐⭐ 5",
            href:"https://api.daily.dev/r/x0OTNXN1m",
            date:"31,Aug,2021",
            readtime:"3min readtime",
            data_item:"general",
            blogAnimated:"animate__zoomIn",
        },
        {
            id:2,
            title:"How to Create pagination with HTML & CSS | Create Advance Pagination in BS | Pagination |Source File",
            text:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore...",
            urlToImage:"./images/blog12.jpg",
            react:"⭐⭐⭐⭐ 4.5",
            href:"https://www.youtube.com/watch?v=3Dxtp8sBs0Q",
            date:"26,Aug,2021",
            readtime:"11min readtime",
            data_item:"frontEnd",
            data_item2:"webDevelopment",
        },
        {
            id:3,
            title:"Why Every Frontend Developer Should Learn CRO",
            text:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore...",
            urlToImage:"./images/blog15.jpg",
            react:"⭐⭐⭐⭐ 4.5",
            href:"https://swd.hashnode.dev/why-every-frontend-developer-should-learn-cro",
            date:"1 6,Aug,2021",
            readtime:"7m readtime",
            data_item:"frontEnd",
            data_item2:"webDevelopment",
        },
      
        {
            id:4,
            title:"Vectorize Image In Illustrator(Show Youtube Video)",
            text:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore...",
            urlToImage:"./images/blog13.jpg",
            react:"⭐⭐⭐⭐ 4.5",
            href:"https://www.youtube.com/watch?v=3p--TZhRV40",
            date:"19,Aug,2021",
            readtime:"16min readtime",
            data_item:"graphic",
        },
      
        {
            id:5,
            title:"&lt;Laz&gt; rendering in Vue to Improve Performance &lt;/Laz&gt;",
            text:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore...",
            urlToImage:"./images/blog5.jpg",
            react:"⭐⭐⭐⭐⭐ 5",
            href:"https://api.daily.dev/r/zaIi1Aw5I",
            date:"18,Aug,2021",
            readtime:"3min readtime",
            data_item:"fontEnd",
            data_item2:"webDevelopment",
        },
        {
            id:6,
            title:"14 Best Chrome Developer Tools 2021",
            text:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore...",
            urlToImage:"./images/blog6.jpg",
            react:"⭐⭐⭐ 3",
            href:"https://api.daily.dev/r/6CPMqnpaj",
            date:"18,Aug,2021",
            readtime:"8min readtime",
            data_item:"general"
        },
        {
            id:7,
            title:"Top 10 Must Know JavaScript Functions",
            text:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore...",
            urlToImage:"./images/blog7.jpg",
            react:"⭐⭐⭐ 3.5",
            href:"https://api.daily.dev/r/Mzs2OBbMG",
            date:"17,Aug,2021",
            readtime:"10min readtime",
            data_item:"backEnd",
            data_item2:"webDevelopment",
        },
        {
            id:8,
            title:"Some cool JavaScript Shorthand that will make your code cleaner than your peer's",
            text:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore...",
            urlToImage:"./images/blog8.jpg",
            react:"⭐⭐⭐ 3",
            href:"https://api.daily.dev/r/vt3s6QplJ",
            date:"16,Aug,2021",
            readtime:"12min readtime",
            data_item:"backEnd",
            data_item2:"webDevelopment",
        },
        {
            id:9,
            title:"Top 10 Web Analytics Software in 2021",
            text:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore...",
            urlToImage:"./images/blog9.jpg",
            react:"⭐⭐⭐⭐ 4.5",
            href:"https://api.daily.dev/r/FytIQHBqO",
            date:"16,Aug,2021",
            readtime:"16min readtime",
            data_item:"general",
        },
        {
            id:10,
            title:"Illustrator tutorial 3D light ball design in illustrator 2019",
            text:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore...",
            urlToImage:"./images/blog10.jpg",
            react:"⭐⭐⭐⭐ 4.5",
            href:"https://www.youtube.com/watch?v=YmpCTg2YfOQ",
            date:"15,Aug,2021",
            readtime:"8min readtime",
            data_item:"graphic",
        },
        {
            id:11,
            title:"How To Use Parallax Scroll Effect with Elementor Free",
            text:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore...",
            urlToImage:"./images/blog11.jpg",
            react:"⭐⭐⭐⭐ 4.5",
            href:"https://www.youtube.com/watch?v=Wt_S3XC5J0o",
            date:"10,Aug,2021",
            readtime:"6min readtime",
            data_item:"frontEnd",
            data_item2:"webDevelopment",
        },
        {
            id:12,
            title:"Functional Programming in JavaScript",
            text:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore...",
            urlToImage:"./images/blog2.jpg",
            react:"⭐⭐⭐⭐ 4.5",
            href:"https://yuricodesbot.hashnode.dev/understanding-functional-programming-in-javascript",
            date:"9,Aug,2021",
            readtime:"6min readtime",
            data_item:"bacckEnd",
            data_item2:"webDevelopment",
        },
        {
            id:13,
            title:"Event Loop in JavaScript:How JavaScript Works Under the Hood",
            text:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore...",
            urlToImage:"./images/blog4.jpg",
            react:"⭐⭐⭐ 3",
            href:"https://api.daily.dev/r/-bjcz7aRn",
            date:"8,Aug,2021",
            readtime:"5min readtime",
            data_item:"backEnd",
            data_item2:"webDevelopment",
        },
        {
            id:14,
            title:"Illustrator Tutorial: Coffee Flat Illustration Design Process",
            text:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore...",
            urlToImage:"./images/blog14.jpg",
            react:"⭐⭐⭐⭐ 4.5",
            href:"https://www.youtube.com/watch?v=VZ5JhNLfbME",
            date:"8,Aug,2021",
            readtime:"7.44m readtime",
            data_item:"graphic",
        },
        {
            id:15,
            title:"How synchronizee the scroll of two divs with JavaScript",
            text:"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore...",
            urlToImage:"./images/blog3.jpg",
            react:"⭐⭐⭐⭐ 4.5",
            href:"https://api.daily.dev/r/vqVKuo9EF0",
            date:"20,Aug,2021",
            readtime:"10min readtime",
            data_item:"backEnd",
            data_item2:"frontEnd",
            data_item3:"webDevelopment",

        },


    ],
}
