let portfolio_data = {
    status:"ok",
    totalResults:9,
    portfolioMainImages:[
        {
            id:1,
            text:"ToDoList Mini project",
            urlToImage:"./images/to-do-list.jpg",
            animated:"animate__fadeInTopLeft",
           
        },
        {
            id:2,    
            text:"Exchange Calculator Responsive Project",
            urlToImage:"./images/exchange.jpg",
            animated:"animate__fadeInDownBig",
        },
        
        {
            id:3,
            text:"Portfolio Responsive Project",
            urlToImage:"./images/portfolioProject.png",
            animated:"animate__fadeInTopRight",
        },
        {
            id:4,
            text:"Add-To-Cart Responsive Project With JQuery",
            urlToImage:"./images/add-to-cart.jpg",
            animated:"animate__fadeInLeftBig",
        },
        {
            id:5,
            text:"Facebook Theme UI Design Project(Static)",
            urlToImage:"./images/facebookUI2.gif",
            animated:"animate__zoomIn",
        },
        {
            id:6,
            text:"MouseOver Clip-path Mini Project",
            urlToImage:"./images/mouseover_clip-path.gif",
            animated:"animate__fadeInRightBig",
        },
        {
            id:7,
            text:"Creation FUTURISM Logo Design",
            urlToImage:"./images/futurism1.jpg",
            animated:"animate__fadeInBottomLeft",
        },
        {
            id:8,
            text:"Admin Dashboard Responsive Project",
            urlToImage:"./images/adminDashboard.jpg",
            animated:"animate__fadeInUpBig",
        },
        {
            id:9,
            text:"Messenger Home Page Project",
            urlToImage:"./images/messenger.jpg",
            animated:"animate__fadeInBottomRight ",
        },
        {
            id:10,
            text:"Direction Aware Button Ripple Effect Project",
            urlToImage:"./images/ripple.gif",
            animated:"animate__fadeInLeftBig",
        },
        {
            id:11,
            text:"Calculator Project",
            urlToImage:"./images/calculator.jpg",
            animated:"animate__zoomIn",
        },
        {
            id:12,
            text:"Mousemove Hexagon Project",
            urlToImage:"./images/hexagon.gif",
            animated:"animate__fadeInRightBig",
        },


    ],
    portfolioPopupBox:[
        {
            id:1,
            projectTitle:"ToDoLis Project",
            projectType:"app",
            client:"Envato",
            languages:"HTML, CSS, Javascript",
            preview:"winwinmaw.com",
            href:"https://codepen.io/WinWinMaw/full/ZEpVoeE",
            urlToImage:"./images/to-do-list.jpg",          
        },
        {
            id:2,
            projectTitle:"Exchange Calculator Project",
            projectType:"app(Responsive)",
            client:"Envato",
            languages:"HTML, CSS, Javascript, jQuery",
            preview:"winwinmaw.com",
            urlToImage:"./images/exchange.jpg",
        },
        {
            id:3,
            projectTitle:"Portofolio Project",
            projectType:"Website(Responsive)",
            client:"Envato",
            languages:"HTML, CSS, Javascript",
            preview:"winwinmaw.com",
            href:'https://testingprofilewebsite2021.netlify.app/',
            urlToImage:"./images/portfolioProject.png",
        },
        {
            id:4,
            projectTitle:"Add To Cart Project",
            projectType:"Website(Responsive)",
            client:"Envato",
            languages:"HTML, CSS, Javascript, jQuery",
            preview:"winwinmaw.com",
            urlToImage:"./images/add-to-cart.jpg",
        },
        {
            id:5,
            projectTitle:"Facebook UI Desing",
            projectType:"Static WebPage",
            client:"Envato",
            languages:"HTML, CSS, Javascript",
            preview:"winwinmaw.com",
            // href:'https://facebookui2021.netlify.app/',
            href:'https://winwinmaw4.github.io/facebook_UI/',
            urlToImage:"./images/facebookUI2.gif",
        },
        {
            id:6,
            projectTitle:"MouseHover Clip-path",
            projectType:"Testing",
            client:"Envato",
            languages:"HTML, CSS, Javascript",
            preview:"winwinmaw.com",
            href:"https://winwinmaw4.github.io/clip_path-lesson/",
            urlToImage:"./images/mouseover_clip-path.gif",
        },
        {
            id:7,
            projectTitle:"Futurism LOGO Desing",
            projectType:"Logo Design",
            client:"Futurism",
            languages:"Photoshop, AI",
            preview:"winwinmaw.com",
            urlToImage:"./images/futurism.jpg",
        },
        {
            id:8,
            projectTitle:"Admin Dashboard Project",
            projectType:"Website(Responsive)",
            client:"MMSIT",
            languages:"HTML, CSS, Javascript, jQuery",
            preview:"winwinmaw.com",
            urlToImage:"./images/adminDashboard.jpg",
        },
        {
            id:9,
            projectTitle:"Messsenger Project",
            projectType:"Website",
            client:"Envato",
            languages:"HTML, CSS, Javascript",
            preview:"winwinmaw.com",
            urlToImage:"./images/messenger.jpg",
        },
        {
            id:10,
            projectTitle:"Direction Aware Ripple Effect",
            projectType:"Testing",
            client:"Envato",
            languages:"HTML, CSS, Javascript",
            preview:"winwinmaw.com",
            href:'https://codepen.io/WinWinMaw/full/ExXVLRE',
            urlToImage:"./images/ripple.gif",
        },
        {
            id:11,
            projectTitle:"Calculator Project",
            projectType:"Website",
            client:"Envato",
            languages:"HTML, CSS, Javascript",
            preview:"winwinmaw.com",
            href:'https://codepen.io/WinWinMaw/full/OJRqRjz',
            urlToImage:"./images/calculator.jpg",
        },
        {
            id:12,
            projectTitle:"Mousemove Hexagon Effect Project",
            projectType:"Testing",
            client:"Envato",
            languages:"HTML, CSS, Javascript",
            preview:"winwinmaw.com",
            href:'https://winwinmaw4.github.io/mousemove_animation_javascript/',
            urlToImage:"./images/hexagon.gif",
        },
    ]
}